#!/usr/bin/env node
// `npm run graph` — validate the dependency graph, print the startup order, and
// (re)generate dev/GRAPH.md with a Mermaid diagram. Validation (unique ports,
// resolvable deps, no cycles) happens inside loadRegistry and throws on error.

import fs from 'node:fs';
import path from 'node:path';
import { loadRegistry, startupWaves, toMermaid } from '../lib/manifest.mjs';
import { REGISTRY_PATH, REPO_ROOT, DEV_DIR } from '../lib/paths.mjs';
import { color, bold, dim } from '../lib/colors.mjs';

let registry;
try {
  registry = loadRegistry(REGISTRY_PATH, REPO_ROOT);
} catch (err) {
  process.stderr.write(color('brightRed', `Dependency validation failed: ${err.message}\n`));
  process.exit(1);
}
const { services } = registry;

process.stdout.write(color('green', '\n✓ dependency graph is valid (no cycles, all deps resolve, ports unique)\n'));

// Startup waves (services within a wave start in parallel).
const waves = startupWaves(services.filter((s) => s.enabled));
process.stdout.write(`${bold('\nStartup order')} (parallel waves)\n\n`);
waves.forEach((wave, i) => {
  const names = wave.map((s) => color(s.color, s.displayName)).join(', ');
  process.stdout.write(`  wave ${i}: ${names}\n`);
});

// Write the Mermaid diagram to dev/GRAPH.md.
const mermaid = toMermaid(services, { includeDisabled: true });
const md = `# AI-Trader — Service Dependency Graph

> Generated by \`npm run graph\`. Do not edit by hand.

Solid nodes are enabled services; dashed nodes are disabled placeholders.

\`\`\`mermaid
${mermaid}
\`\`\`

## Startup order (parallel waves)

${waves.map((w, i) => `${i}. ${w.map((s) => s.displayName).join(', ')}`).join('\n')}
`;
const outPath = path.join(DEV_DIR, 'GRAPH.md');
fs.writeFileSync(outPath, md);
process.stdout.write(dim(`\nWrote ${path.relative(REPO_ROOT, outPath)}\n\n`));
